### ISSUE TITLE
Missing .pt file 

### ISSUE THREAD

**Issue by tnoya001** [duskvirkus/alias-free-gan-pytorch-lightning#31]
Hi. If I follow all  your cells and instructions in order, I get this once I reach the second cell of "Generate Single Images" 

Using Alias-Free GAN version: 1.0.0
Invalid path /content/drive/MyDrive/colab-gpu-alias-free/alias-free-gan/results/training-000005/000145-epoch-checkpoint.pt is not a .pt model file.

I cannot find that file anywhere or any other .pt file for that matter. 

Thanks.

**Comment by duskvirkus** [comment]
Oh that was just a checkpoint file I was using for testing. I didn't bothering sharing it as a sample because it's was only trained for a little while and it's the not a great model. Happy to share it if you like but you can also download rosinality's ffhq model here: https://aliasfreegan.sfo3.cdn.digitaloceanspaces.com/rosinality-ffhq-800k.pt

I'm still training a 1024 on wikiart landscapes so which I'll put up as the example model as soon as it's done.

Thanks for the feedback I'll try to put up a notebook where the default model works.

**Comment by tnoya001** [comment]
Completely missed the rosinality pt file. I have it now. All good. Thanks and sorry for the trouble.

**Comment by afiaka87** [comment]
> Oh that was just a checkpoint file I was using for testing. I didn't bothering sharing it as a sample because it's was only trained for a little while and it's the not a great model. Happy to share it if you like but you can also download rosinality's ffhq model here: https://aliasfreegan.sfo3.cdn.digitaloceanspaces.com/rosinality-ffhq-800k.pt
> 
> I'm still training a 1024 on wikiart landscapes so which I'll put up as the example model as soon as it's done.
> 
> Thanks for the feedback I'll try to put up a notebook where the default model works.

Do you have a timespan on how long the wikiart checkpoint will take to train? That sounds very interesting!

**Comment by duskvirkus** [comment]
@tnoya001 Latest release has working notebook with rosinality model. https://github.com/duskvirkus/alias-free-gan/blob/stable/notebooks/GPU_Inference_Alias_Free_GAN.ipynb

@afiaka87 Who know's I'm guessing another week or two but I'm having problems with occasional mode collapse and it also depends on what gpus I get on colab for training.
